name: hw2
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider:
  flutter_riverpod:
  riverpod_annotation:
  freezed_annotation:
  json_annotation: ^4.8.0
  flutter_svg:
  intl:

dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  riverpod_generator:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recipes.json
    - assets/images/
    - assets/icons/
    
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

