name: hw2
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.2.0
  riverpod_annotation: ^1.2.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.1
  intl: ^0.18.0
  dio: ^5.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_network_connectivity: ^0.0.6
  rive: 0.10.3
  camera: 0.10.4
  swipe_image_gallery: ^0.8.3
  go_router: ^6.5.3
  flutter_tflite: ^1.0.1
  tflite_flutter_helper_plus: ^0.0.2

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^1.2.0
  hive_generator: ^2.0.0
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recipes.json
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/model/
    
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

